### ISSUE TITLE
Dependency on old unmaintained version of javamail 1.6.2 should be updated to use jakarta.mail

### ISSUE THREAD

**Issue by debanshu** [networknt/openapi-parser#43]
The current pom depends on the older unmaintained `javax.mail` namespace 

(Even though the README says this project does not depend on javax.mail)

```xml

<dependency>
    <groupId>com.sun.mail</groupId>
    <artifactId>javax.mail</artifactId>
    <version>${version.javamail}</version>
</dependency>
        
<version.javamail>1.6.2</version.javamail>
```

I think we should either remove this dependency (to stay true to the README) or update to use the currently maintained `jakarta.mail` namespace

```xml
<dependency>
  <artifactId>jakarta.mail</artifactId>
  <groupId>com.sun.mail</groupId>
</dependency>
```

**Comment by AndreasALoew** [comment]
I fully second this request:

We are in the process of migrating our application from Java EE 8 to Jakarta EE 10, and **cannot remove the old "javax.mail" dependency** from our build due to the compile-time use of the following "old" javax-style imports:

```
import javax.mail.internet.AddressException;
import javax.mail.internet.InternetAddress;
```

in class ``com.networknt.oas.validator.ValidatorBase``.

In order to stay independent from the javax/jakarta package prefix issue, I think it would be best to **copy the source code of these two classes** and provide them as ``com.networknt.oas.validator.AddressException`` and ``com.networknt.oas.validator.InternetAddress`` - but please note that this involves **changing your ``LICENSE``** from Eclipse Public License (EPL) 1.0 to **EPL 2.0**, as the current code of the javax/jakarta mail implementation (https://github.com/jakartaee/mail-api/tree/master/api/src/main/java/jakarta/mail/internet) is licensed under

```
SPDX-License-Identifier: EPL-2.0 OR GPL-2.0 WITH Classpath-exception-2.0
```

It clearly would be a pity to be forced to fork this one more time (as it's already a fork from [kaizen-openapi-parser](https://github.com/RepreZen/KaiZen-OpenApi-Parser/tree/master/kaizen-openapi-parser)) just to get rid of the "javax" dependency for legal reasons.

Many thanks for considering to make this important change to ensure your code is future-proof!

**Comment by AndreasALoew** [comment]
@stevehu , when do you plan to release the next official build (i.e. 2.1.38)? The patch has been in the snapshot version now for quite a while (almost 6 weeks), and I would need an official release version of openapi-parser if possible to build a new release of our own software from until the end of next week (Nov 7th/8th)...

many thx in advance! 😄

**Comment by stevehu** [comment]
We are releasing snapshot versions frequently for test with several users. Currently, there are several issues that we are working on. Once those issues are resolved, we can have another release. Hopefully, within two weeks. Thanks.
